name: mermaid

channels:
    - conda-forge
    - anaconda
    - uncbiag

dependencies:
    - python==3.7
    - pytorch
    - mermaid
    - pip:
        - matplotlib
        - pyyaml
        - sphinx-gallery
